### PR TITLE
Provide metadata information through Batch job parameters

### PR DESCRIPTION
**Pull request by scwatts**
Changes:

- add workflow metadata to Batch job parameters for downstream operations
- include only Portal run ID, workflow name, workflow version, output base directory for now
- workflow output directories now set in Lambdas and passed to run.sh in Batch job command
- configure workflow name and version through the respective settings class

Example:

_CW log /aws/lambda/event-format-observer (2023/09/07/[$LATEST]03ce49d6616e4a449c768b3cb31834f0)_

> `.Records[0].body | fromjson | .detail.parameters`

```json
{
  "portal_run_id": "20230908wgsaaaaa",
  "workflow": "oncoanalyser_wgs",
  "version": "v0.1.0",
  "output": {"output_directory": "s3://umccr-temp-dev/analysis_data/SBJ00910/oncoanalyser/20230908wgsaaaaa/wgs/L2100746__L2100745"}
}
```

### CODE REVIEW

**Comment by scwatts** [comment]
Force pushing to rebase on top of main

**Comment by victorskl** [comment]
Linking ditto convo behind change request
https://umccr.slack.com/archives/CP356DDCH/p1694066750376839

**Comment by victorskl** [comment]
[Portal Release - Ocicat: Implement Portal automation integration for oncoanalyser](https://trello.com/c/sZFv7FhZ/1488-portal-release-ocicat-implement-portal-automation-integration-for-oncoanalyser)

**Review by victorskl — APPROVED** [review]
LGTM! thank you

**Comment by victorskl** [comment]
@reisingerf tick pls, here too

**Comment by scwatts** [comment]
Force pushing to rebase on main again

**Comment by victorskl** [comment]
_(May the force be with you..!)_

Another "rebase" user here, Flo. :) wink, wink

**Review by reisingerf — APPROVED** [review]

**Pull request merged**
