### PR TITLE
Add cost allocation tags and propagate the tags

### LINKED ISSUE #85: Use --tag on submit_job for cost allocation purposes
Add a `RunId` tag parameter (and corresponding value) to [this and/or other submit_job calls](https://github.com/umccr/nextflow-stack/blob/b3f2f360ac3b2fd2dcc7119871333e419c64e2c4/application/pipeline-stacks/oncoanalyser/lambda_functions/batch_job_submission/lambda_code.py#L61). Also experiment with `propagate-tags`: https://docs.aws.amazon.com/cli/latest/reference/batch/submit-job.html

/cc @scwatts @reisingerf @andrewpatto

### PR DESCRIPTION
**Pull request by brainstorm**
Fixes #85 

@scwatts Please deploy/test, I'm not breaking your pipes accidentally ;)

@reisingerf Would you add the `SubStack` key to better track which sub-pipeline is costing? I see there's other pipes such as sash, etc... but I'm not sure if there's a establish those accordingly?

### CODE REVIEW

**Comment by reisingerf** [comment]
Would you want to add a execution specific tag (i.e. `portal_run_id` based) while at it?

**Comment by brainstorm** [comment]
> Would you want to add a execution specific tag (i.e. `portal_run_id` based) while at it?

That! I knew I was missing something XD

**Comment by reisingerf** [comment]
And a minor one for @scwatts : do we want to rename this stack to something more customised/specific to OA rather than generic Nextflow?

**Comment by scwatts** [comment]
Sorry, got caught up today - LGTM thanks Roman!

I think having the generic 'NextflowStack' name is okay since we might end up running WISP etc here over the next couple of months.

One minor request, can we either change the 'SubStack' values to match pipeline names **[here](https://github.com/umccr/nextflow-stack/blob/main/application/application-stack.ts#L38-L57)** or just have oncoanalyser shown as 'Oncoanalyser'?

**Review by scwatts — APPROVED** [review]

**Review by reisingerf — APPROVED** [review]

**Pull request merged**
